### ISSUE TITLE
Update CloudStack Go SDK and enable tests

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack-terraform-provider#101]
Refer https://github.com/apache/cloudstack-terraform-provider/pull/100 and upgrade the go sdk and enable the tests.

**Comment by fabiomatavelli** [comment]
This was done in #71

**Comment by CodeBleu** [comment]
Per @fabiomatavelli above, I'm closing this issue as #71 fixes #101 (this)

**Comment by CodeBleu** [comment]
Per @fabiomatavelli above, I'm closing this issue as https://github.com/apache/cloudstack-terraform-provider/pull/71 fixes https://github.com/apache/cloudstack-terraform-provider/issues/101 (this)
