### ISSUE TITLE
Can Discussions be enabled on this repo?

### ISSUE THREAD

**Issue by CodeBleu** [apache/cloudstack-terraform-provider#102]
@rohityadavcloud Figured it might be good to have the `Discussions` on this repo for when there are topics or questions, that doesn't necessarily need to be an `issue`

**Comment by CodeBleu** [comment]
@kiranchavala @vishesh92 @rohityadavcloud  I see that the v0.5.0 milestone is 100%.  That is awesome!  Just wondering when this is going to be released and published?
![image](https://github.com/apache/cloudstack-terraform-provider/assets/400979/58849413-3ec7-423b-8334-c1fa47081114)

**Comment by rohityadavcloud** [comment]
@CodeBleu we generally discuss on mailing lists that would be encouraged and we also have all general CloudStack discussions here https://github.com/apache/cloudstack/discussions

Kiran had started a discussion on the dev and users mailing list and then the alpha (pre RC) is currently out for testing for any blockers or regressions https://registry.terraform.io/providers/cloudstack/cloudstack/0.5.0-pre

**Comment by kiranchavala** [comment]
@CodeBleu I am planning to cut 0.5 RC 1 and start the voting process on  April 1st

**Comment by CodeBleu** [comment]
I see v0.5.0 on Terraform Registry,  but this repo  release section still shows a 2 year old v0.4.0

**Comment by rohityadavcloud** [comment]
The v0.5.0 RC is up for vote @CodeBleu have you subscribed to the dev mailing list ? https://cloudstack.apache.org/mailing-lists

Once the vote passes, the release manager (@kiranchavala) will publish the git tag and create a Github release.

**Comment by rohityadavcloud** [comment]
Closing this as https://github.com/apache/cloudstack/discussions can be used and Issue on this repo can be used for any other specific things to this repo/sub-project.
