### ISSUE TITLE
Add kubernetes service related resources to terraform

### ISSUE THREAD

**Issue by harikrishna-patnala** [apache/cloudstack-terraform-provider#13]
This is an enhancement ticket to add support for CloudStack Kubernetes service through Terraform. We need to add CRUD operations for CKS in Cloudstack terraform provider.

**Comment by svenvogel** [comment]
@davidjumani @harikrishna-patnala is this implemented already to use terraform for the cks?

**Comment by lukasmrtvy** [comment]
Any progress on this ? Thanks

**Comment by lukasmrtvy** [comment]
Added in 4.16.1 https://github.com/apache/cloudstack-go/pull/33/files#diff-b28a8efd29239ed5505919480c05f97432719c96d98cd370752bf0d1925020

ping @harikrishna-patnala

**Comment by harikrishna-patnala** [comment]
Hi @lukasmrtvy, this is not yet implemented in terraform providers, someone needs to pick this up. @davidjumani may take this based on our recent conversation.
