### ISSUE TITLE
Cannot create load balancer rule - Root resource was present, but now absent.

### ISSUE THREAD

**Issue by softsankar** [apache/cloudstack-terraform-provider#131]
Not able to create load balancer by attaching multiple instances to a load balancer rules. Tried to synchronize the load balancer rule creation one after another. But NO luck.

**Comment by kiranchavala** [comment]
@softsankar 

Could you please paste the terraform code that you trying to achieve?

Currently you can create a loadbalancer rule via terraform and attach to multiple instances by using the 

member_ids parameter

```

resource "cloudstack_loadbalancer_rule" "default" {
  name          = "loadbalancer-rule-1"
  description   = "Loadbalancer rule 1"
  ip_address_id = "30b21801-d4b3-4174-852b-0c0f30bdbbfb"
  algorithm     = "roundrobin"
  private_port  = 80
  public_port   = 80
  member_ids    = ["f8141e2f-4e7e-4c63-9362-986c908b7ea7"]
}
```

**Comment by rohityadavcloud** [comment]
Closing this on inactivity, the questions has been answered. @softsankar please re-open if you can advise more details on reproducing the issue (if any).
