### ISSUE TITLE
Release with darwin/arm64 Support

### ISSUE THREAD

**Issue by hrak** [apache/cloudstack-terraform-provider#14]
### Terraform Version

Terraform v1.0.10
on darwin_arm64

### Affected Resource(s)

N/A

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

Able to install provider on darwin/arm64 platform without manually compiling.

### Actual Behavior

Error during terraform init:
```
Error: Incompatible provider version

Provider registry.terraform.io/cloudstack/cloudstack v0.4.0-pre does not have a package
available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all providers are available
for all platforms. Other versions of this provider may have different platforms supported.
```
Need to manually compile and install provider for darwin/arm64 support.

### Steps to Reproduce

    terraform init

### References

- https://github.com/hashicorp/terraform/issues/27257

**Comment by rhtyd** [comment]
@hrak can you test/try again with https://registry.terraform.io/providers/cloudstack/cloudstack/latest ?

**Comment by rhtyd** [comment]
Based on another users's testing, closing the issue of github release artifacts fixed this.
