### ISSUE TITLE
Issues with CloudStack version number and checksum

### ISSUE THREAD

**Issue by synergiator** [apache/cloudstack-terraform-provider#15]
Happy to try out the latest release; found the following:

1. The README example of this repo specifies the provider version to be "0.4.0". However, Terraform can't download it: indeed, lookup of the[ source URL](https://registry.terraform.io/v1/providers/cloudstack/cloudstack/versions) in the Hashicorp Terraform Registry reveals it's "0.4.0-pre" and not "0.4.0". Maybe this should be changed in the docs. Also, in terms of repo tags, the latest one is just "0.3.0".
2. After changing the version, I get a checksum error (run twice, same wrong checksum). 

Execution environment: Docker/Gitlab/GitLab's Terraform wrapper script.

```
╷
│ Error: Failed to install provider
│ 
│ Error while installing cloudstack/cloudstack v0.4.0-pre: checksum list has
│ unexpected SHA-256 hash
│ c031e5466360394787d1c408c853a853ed4d6e171a611ae30c0c5111f20e21b9 (expected
│ a36b77f35a0eeff9fbd5bb2fd68b986bae6023ac49e6f035ea43deec4043b3f4)
```

While trying same setup with the [hard fork release by Orange](https://github.com/orange-cloudfoundry/terraform-provider-cloudstack) (thanks @ArthurHlt for linking to this repo!),  I do not get the above checksum error.

```
- Installed orange-cloudfoundry/cloudstack v0.5.1 (self-signed, key ID B910DF52F90CB360)
Partner and community providers are signed by their developers.
```

After that though I get another error which is for sure not to consider in this context, but to prevent with a proper usage example as Terraform's error messages are sometimes not very helpful.

```
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/cloudstack: provider registry registry.terraform.io does not have
│ a provider named registry.terraform.io/hashicorp/cloudstack
│ 
│ Did you intend to use orange-cloudfoundry/cloudstack? If so, you must
│ specify that source address in each module which requires that provider. To
│ see which modules are currently depending on hashicorp/cloudstack, run the
│ following command:
│     terraform providers
```

**Comment by synergiator** [comment]
UPD - as it seems currently there is no possibility at all to use this provider?

In an old project:

```
provider "cloudstack" {
  config  = var.cloudmonkey_config_file
  profile = var.cloudmonkey_profile
}
```

Error, similarly:

```
Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/cloudstack: provider registry registry.terraform.io does not have a provider named registry.terraform.io/hashicorp/cloudstack
```

**Comment by StepBee** [comment]
Same issue here and mentioned already before.

It's possible to place the provider (binary terraform-provider-cloudstack_v0.4.0-pre) locally (create the folders):
~/.terraform.d/plugins/registry.terraform.io/cloudstack/cloudstack/0.4.0-pre/linux_amd64/

checksum is not compared online then and you can use the provider locally.

But it's only a workaround and the registration to the terraform provider list should be fixed.

**Comment by harikrishna-patnala** [comment]
yes @synergiator , @StepBee mentioned workaround can be applied. We are trying to push the binaries again to see if the issue still exists.

**Comment by rhtyd** [comment]
@synergiator @StepBee can you try again with:
https://registry.terraform.io/providers/cloudstack/cloudstack/latest

**Comment by StepBee** [comment]
I am not sure if i am doing something wrong, but now i get the error
`no available releases match the given constraints 0.4.0-rc1`

**Comment by harikrishna-patnala** [comment]
@StepBee Can you please check if .tf file has the proper version mentioned. Or it could be caching issue, please try again.

I just did the terraform init and worked fine

harikrishna@harikrishna:~/go/src/github.com/apache/provider$ terraform init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of cloudstack/cloudstack from the dependency lock file
- Using previously-installed cloudstack/cloudstack v0.4.0-rc1

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

**Comment by StepBee** [comment]
@harikrishna-patnala thanks for the hint - i tested on a different system and can confirm it's working.

**Comment by rhtyd** [comment]
Closing on your remark.
