### ISSUE TITLE
Understanding implications of the legacy SDK notification

### ISSUE THREAD

**Issue by synergiator** [apache/cloudstack-terraform-provider#20]
In the log output there is the following notification:

```
 Provider "registry.terraform.io/cloudstack/cloudstack" produced an invalid plan 
for module....., but we are tolerating it because it is using the legacy plugin SDK.
```
Does it mean it's SDK level 1.x?

**Comment by harikrishna-patnala** [comment]
@synergiator I'm also not aware of this but on quick search on google, came to know this error comes from terraform core when it finds that legacy SDK plugin is used. May be this is related to terraform version being used with this provider which is v0.12.0, but still is backward compatible wrt terraform version.

**Comment by harikrishna-patnala** [comment]
@synergiator can you please let me know if anything else we need here or we can close this

**Comment by synergiator** [comment]
thx

**Comment by frittentheke** [comment]
@harikrishna-patnala did you come to a conclusion about the root cause then?
Is there really nothing to be done on the providers side?

I just ran into a similar issue with the openstack provider, see https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1307
