### ISSUE TITLE
Instance cannot be expunged, only destroyed

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack-terraform-provider#24]
When invoking the 'destroy' command to a running VM, it cannot be expunged as well. Which causes other issues, for example the VM's network cannot be destroyed too since it's still connected to the destroyed VM.

```
Error: Error deleting network TERRAFORM-isolated1: Undefined error: {"errorcode":530,"errortext":"Failed to delete network"}
```

**Comment by harikrishna-patnala** [comment]
@vladimirpetrov I see that there is "expunge" param that we can set in terraform VM resource configuration.resource 
"cloudstack_instance" "VM1" {
name = "VM1"
service_offering = "Small Instance"
template = cloudstack_template.Template.id
network_id = cloudstack_network.N1.id
zone = "${var.zoneId}"
**expunge = true**
}

I tried this with destroy command and it expunged the VM. can you please try that as well.

**Comment by vladimirpetrov** [comment]
This parameter fixes the problem, closing the issue.
