### ISSUE TITLE
K8s  cluster creation is failing beacuse of timeout

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack-terraform-provider#40]
Issue
------
Currently k8s cluster creation is failing because of a default timeout  15 min
-

cloudstack_kubernetes_cluster.cluster1: Still creating... [15m0s elapsed]
╷
│ Error: Timeout while waiting for async job to finish
│
│   with cloudstack_kubernetes_cluster.cluster1,
│   on main.tf line 8, in resource "cloudstack_kubernetes_cluster" "cluster1":
│    8: resource "cloudstack_kubernetes_cluster" "cluster1" {
│

The workaround for this is to include timeout for "resource_cloudstack_kubernetes_cluster.go" file 

	Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(45 * time.Minute),
		},
		
		
		and in the terraform (main.tf) include the timeout value
		
 resource "cloudstack_kubernetes_cluster" "cluster1" {
  name = "kirank8s"
  description = "Created using Terraform"
  zone = "10b647b0-da6d-4120-b908-a9ffa31b91bf"
  kubernetes_version = "5bc1aa83-c2ff-46be-8eb9-f97ad28d3399"
  service_offering = "98d7da5b-437e-43ff-b4ca-6ed612bb011f"
  size = 1

  timeouts {
    create = "60m"
    
  }

**Comment by harikrishna-patnala** [comment]
@kiranchavala you can use generic the timeout argument in "cloudstack" provider details in your .tf configuration or in the environment variable.

Please refer https://registry.terraform.io/providers/cloudstack/cloudstack/latest/docs#timeout

I hope it will solve your problem, let me know if I can close this ticket.

**Comment by kiranchavala** [comment]
Hi @harikrishna-patnala  thanks for the workaround 

It's working fine, you may close the ticket
