### ISSUE TITLE
An argument named "cluster" is not expected here when creating a VM from particular cluster 

### ISSUE THREAD

**Issue by dseralathan** [apache/cloudstack-terraform-provider#61]
Error: Unsupported argument in resource "cloudstack_instance
│ 
│   on vm.tf line 12, in resource "cloudstack_instance" "node02":
│   12:   cluster          = "cluster01"
│ 
│ An argument named "cluster_id" is not expected here.

How we can create a VM on particular cluster ., we have two cluster on same Zone

**Comment by kiranchavala** [comment]
Hi @yashi4engg 

Currently cluster_id parameter is not available  when using terraform to deploy a vm.

https://registry.terraform.io/providers/cloudstack/cloudstack/latest/docs/resources/instance.

We will include the option in next release

**Comment by yashi4engg** [comment]
@kiranchavala  - Do we planning any tentative time for new release

**Comment by harikrishna-patnala** [comment]
@yashi4engg yes, after CloudStack 4.19 release we will plan a new release for terraform provider and address possible issues and improvements.
