### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by poddm** [apache/cloudstack-terraform-provider#63]
Hi @rohityadavcloud , @harikrishna-patnala - what is the status of this project?

i see a lot of API integrations (and client enhancements) that haven't been released.  Do you plan to release anymore updates?

**Comment by rohityadavcloud** [comment]
Hi @poddm yes this is very much active, and we've a few fixes; however we're lacking another release soon. We've planned for a release in Q3/Q4 this year. We were hoping to focus on 4.18.1 and 4.19.0 first and get the new features/APIs via the go sdk (https://github.com/apache/cloudstack-go). cc @harikrishna-patnala @weizhouapache @shwstppr @DaanHoogland @kiranchavala

**Comment by rohityadavcloud** [comment]
I've created a new milestone to track the next release - https://github.com/apache/cloudstack-terraform-provider/milestone/2

Closing on the remark that the original question has been answered. I'll also look if there a way to automate publishing latest builds as alpha/beta releases for anybody to try the latest/bleeding edge.

**Comment by poddm** [comment]
Sounds great.  thanks for creating that.
