### ISSUE TITLE
Terraform plugin SDK update

### ISSUE THREAD

**Issue by poddm** [apache/cloudstack-terraform-provider#66]
Looks like cloudstack is using the "legacy Terraform plugin SDK".   To ensure terraform core compatibility we should look at upgrading to SDK v2.

Current: `github.com/hashicorp/terraform v0.12.0`
- https://github.com/apache/cloudstack-terraform-provider/blob/main/go.mod#L9

[v1-upgrade-guide](https://developer.hashicorp.com/terraform/plugin/sdkv2/guides/v1-upgrade-guide)

> As of September 2019, Terraform provider developers importing the Go module github.com/hashicorp/terraform, known as Terraform Core, should switch to github.com/hashicorp/terraform-plugin-sdk, the Terraform Plugin SDK, instead.
..
> We will use the term "legacy Terraform plugin SDK" when referring to the version of Terraform Core imported and used by providers.

[Upgrading to the latest Terraform SDK](https://developer.hashicorp.com/terraform/plugin/sdkv2/guides/terraform-0.12-compatibility#upgrading-to-the-latest-terraform-sdk)

At the time of the Terraform 0.12 release, the Terraform SDK is a set of sub-directories inside the Terraform Core repository. Therefore upgrading to the latest Terraform SDK involves upgrading all of the dependencies on Go packages with the prefix github.com/hashicorp/terraform/ to a version with support for the new provider protocol.

NOTE: The SDK is now its own Go module. Existing providers should upgrade to at least v0.12.7 before [switching to the standalone SDK](https://developer.hashicorp.com/terraform/plugin/sdkv2/guides/v1-upgrade-guide). This is to isolate issues between Terraform SDK v0.11 and v0.12, and the standalone SDK. New providers should vendor the standalone SDK from the start.

**Comment by fabiomatavelli** [comment]
This was implemented by #71
