### ISSUE TITLE
Support hot resize of disk

### ISSUE THREAD

**Issue by vdombrovski** [apache/cloudstack-terraform-provider#72]
Currently, whenever the size of a volume changes, the disk gets detached before resizing. 

https://github.com/apache/cloudstack-terraform-provider/blob/main/cloudstack/resource_cloudstack_disk.go#L217

However Cloudstack 4.17 supports dynamic data disk resising without detaching it, which means we don't always need to detach / attach disk in certain cases (e.g. when only size changes). It would be cool to have this feature in the TF provider as well.

**Comment by kiranchavala** [comment]
@vdombrovski 

I have cross-checked the issue and disk resize is happening when you use a custom disk offering

![Screenshot 2024-03-05 at 5 24 01 PM](https://github.com/apache/cloudstack-terraform-provider/assets/1401014/dee7763c-e127-4db8-812b-9404010d4f55)



Terraform is performing the  resize operation :

```
  # cloudstack_disk.test-disk will be updated in-place
  ~ resource "cloudstack_disk" "test-disk" {
        id                 = "d5a695d5-7bd7-46f8-b63f-be81152584bf"
        name               = "test-disk"
      ~ size               = 5 -> 10
        tags               = {}
        # (6 unchanged attributes hidden)
    }
```
    
    

Please make sure to use a custom disk offering

```
resource "cloudstack_disk" "default" {
  name               = "test-disk"
  attach             = "true"
  disk_offering      = "custom"
  size               = 50
  virtual_machine_id = "server-1"
  zone               = "zone-1"
}
```

**Comment by btzq** [comment]
Hi There, 

When we resize a disk, we noticed that although terraform says its 'modified', in reality, Terraform will unmount, destroy the volume, recreate a new one. (We have to manually reattach it back after). 

Will his fix resolve this as well?

Also, can terraform mount a volume for us automatically? Or do we have to manually mount it oureselves all the time?

**Comment by kiranchavala** [comment]
@btzq 

Yes with fix  the resize job  will be done without any detach operation.

**Comment by btzq** [comment]
@kiranchavala great! Cant wait to test it in V0.5!
