### ISSUE TITLE
Terraform Github Actions Integration Tests failing

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack-terraform-provider#98]
Most recent commit shows the integration/acceptance tests via GA are still failing:
https://github.com/apache/cloudstack-terraform-provider/actions/runs/8188070488/job/22389899997

Do we also need or have (already) any CI integration with trillian?

**Comment by vishesh92** [comment]
There are only 2 tests failing as of now. The fix requires us to update cloudstack-go SDK to latest version (v2.15.0) which can cause other breaking changes. Should we move this to milestone 0.6.0?
